# Make sure that in production no passwords are hardcoded in the codebase.

services:
  database:
    image: postgres:15
    container_name: prisma_postgres
    restart: always
    env_file:
      - ./apps/backend/.env
    environment:
      POSTGRES_USER: letseat
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@letseat.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: