services:
  database:
    image: postgres:15
    container_name: prisma_postgres
    restart: always
    env_file:
      - ./apps/backend/.env
    environment:
      POSTGRES_USER: letseat
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: